"use client"
import { Construction } from "lucide-react";

import { Button } from "@/components/ui/button";
import Link from "next/link";

const buttons = [
  {
    title: "Construction Company",
    icon: Construction,
    href: "/builds/construction",
  },
  {
    title: "Epoxy Flooring Company",
    icon: Construction,
    href: "/builds/epoxy-flooring",
  },
  {
    title: "Digital Agency",
    icon: Construction,
    href: "/builds/digital-agency",
  },
  
];

export default function Home() {
  return (
    <section className="py-32">
      <div className="container">
        <div className="mx-auto flex max-w-7xl flex-col items-center gap-10">
          <div className="flex max-w-4xl flex-col gap-6">
            <h1 className="text-4xl font-semibold md:text-5xl">
              Welcome to Qwendean-4B Generation Outputs
            </h1>
            <p className="text-muted-foreground max-w-4xl text-lg">
              These pages you see below were generated by Qwendean-4B, section-by-section.
              These are exact generation outputs, with no human edits or modifications on layout. Each section is generated independently, so there may be some inconsistencies between sections. However, this is a true representation of the capabilities of Qwendean-4B.
              Since to reduce training noise, we removed all the copywriting content from the training data, you will see that all the copywriting content is very generic and placeholder-like. Therefore whereever possible we have added some placeholder content to make the pages look more realistic and complete.
            </p>
          </div>
          <div className="grid w-full max-w-4xl grid-cols-1 gap-6 sm:grid-cols-2 md:gap-8">
            {buttons.map((button, index) => {
              const Icon = button.icon;
              return (
                <Link
                  key={index}
                  href={button.href}
                  className="group flex w-full flex-row justify-center gap-3 rounded-lg border p-3 text-left hover:bg-muted hover:text-primary"
                >
                    <Icon className="size-5" />
                    <h2 className="text-lg font-medium">{button.title}</h2> 
                </Link>
              );
            })}
          </div>
        </div>
      </div>
    </section>
  );
};

